
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DemandGraphEditor(object):
    def setupUi(self, DemandGraphEditor):
        DemandGraphEditor.setObjectName(_fromUtf8("DemandGraphEditor"))
        DemandGraphEditor.setWindowModality(QtCore.Qt.ApplicationModal)
        DemandGraphEditor.resize(443, 338)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/graph.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DemandGraphEditor.setWindowIcon(icon)
        DemandGraphEditor.setStyleSheet(_fromUtf8("QWidget, QMenuBar::item {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #c5d8ef, stop: 1 #89a5c3);\n"
"}\n"
"\n"
"QLabel, QSlider {\n"
"    background-color: transparent;\n"
"}"))
        self.centralwidget = QtGui.QWidget(DemandGraphEditor)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.startTime = QtGui.QLineEdit(self.centralwidget)
        self.startTime.setObjectName(_fromUtf8("startTime"))
        self.gridLayout.addWidget(self.startTime, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.endTime = QtGui.QLineEdit(self.centralwidget)
        self.endTime.setObjectName(_fromUtf8("endTime"))
        self.gridLayout.addWidget(self.endTime, 0, 3, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.graphArea = QtGui.QScrollArea(self.centralwidget)
        self.graphArea.setWidgetResizable(False)
        self.graphArea.setObjectName(_fromUtf8("graphArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 398, 230))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.graphArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.graphArea)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 4)
        DemandGraphEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DemandGraphEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 443, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        DemandGraphEditor.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(DemandGraphEditor)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        DemandGraphEditor.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSelect = QtGui.QAction(DemandGraphEditor)
        self.actionSelect.setCheckable(True)
        self.actionSelect.setChecked(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/select.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelect.setIcon(icon1)
        self.actionSelect.setObjectName(_fromUtf8("actionSelect"))
        self.actionVM = QtGui.QAction(DemandGraphEditor)
        self.actionVM.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/computer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVM.setIcon(icon2)
        self.actionVM.setObjectName(_fromUtf8("actionVM"))
        self.actionEdge = QtGui.QAction(DemandGraphEditor)
        self.actionEdge.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/edge.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdge.setIcon(icon3)
        self.actionEdge.setObjectName(_fromUtf8("actionEdge"))
        self.actionNew_System = QtGui.QAction(DemandGraphEditor)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/page.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_System.setIcon(icon4)
        self.actionNew_System.setObjectName(_fromUtf8("actionNew_System"))
        self.actionOpen_System = QtGui.QAction(DemandGraphEditor)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_System.setIcon(icon5)
        self.actionOpen_System.setObjectName(_fromUtf8("actionOpen_System"))
        self.actionSave_System = QtGui.QAction(DemandGraphEditor)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/cd.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_System.setIcon(icon6)
        self.actionSave_System.setObjectName(_fromUtf8("actionSave_System"))
        self.actionSave_System_As = QtGui.QAction(DemandGraphEditor)
        self.actionSave_System_As.setObjectName(_fromUtf8("actionSave_System_As"))
        self.actionExit = QtGui.QAction(DemandGraphEditor)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionDemandStorage = QtGui.QAction(DemandGraphEditor)
        self.actionDemandStorage.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/storage.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDemandStorage.setIcon(icon7)
        self.actionDemandStorage.setObjectName(_fromUtf8("actionDemandStorage"))
        self.menuFile.addAction(self.actionNew_System)
        self.menuFile.addAction(self.actionOpen_System)
        self.menuFile.addAction(self.actionSave_System)
        self.menuFile.addAction(self.actionSave_System_As)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionNew_System)
        self.toolBar.addAction(self.actionOpen_System)
        self.toolBar.addAction(self.actionSave_System)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSelect)
        self.toolBar.addAction(self.actionVM)
        self.toolBar.addAction(self.actionDemandStorage)
        self.toolBar.addAction(self.actionEdge)

        self.retranslateUi(DemandGraphEditor)
        QtCore.QObject.connect(self.actionSelect, QtCore.SIGNAL(_fromUtf8("triggered()")), DemandGraphEditor.toggleSelect)
        QtCore.QObject.connect(self.actionVM, QtCore.SIGNAL(_fromUtf8("triggered()")), DemandGraphEditor.toggleVM)
        QtCore.QObject.connect(self.actionEdge, QtCore.SIGNAL(_fromUtf8("triggered()")), DemandGraphEditor.toggleEdge)
        QtCore.QObject.connect(self.actionNew_System, QtCore.SIGNAL(_fromUtf8("triggered()")), DemandGraphEditor.New)
        QtCore.QObject.connect(self.actionOpen_System, QtCore.SIGNAL(_fromUtf8("triggered()")), DemandGraphEditor.Open)
        QtCore.QObject.connect(self.actionSave_System, QtCore.SIGNAL(_fromUtf8("triggered()")), DemandGraphEditor.Save)
        QtCore.QObject.connect(self.actionSave_System_As, QtCore.SIGNAL(_fromUtf8("triggered()")), DemandGraphEditor.SaveAs)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), DemandGraphEditor.close)
        QtCore.QObject.connect(self.actionDemandStorage, QtCore.SIGNAL(_fromUtf8("triggered()")), DemandGraphEditor.toggleDemandStorage)
        QtCore.QObject.connect(self.startTime, QtCore.SIGNAL(_fromUtf8("editingFinished()")), DemandGraphEditor.changeTime)
        QtCore.QObject.connect(self.endTime, QtCore.SIGNAL(_fromUtf8("editingFinished()")), DemandGraphEditor.changeTime)
        QtCore.QMetaObject.connectSlotsByName(DemandGraphEditor)
        DemandGraphEditor.setTabOrder(self.graphArea, self.startTime)
        DemandGraphEditor.setTabOrder(self.startTime, self.endTime)

    def retranslateUi(self, DemandGraphEditor):
        DemandGraphEditor.setWindowTitle(_translate("DemandGraphEditor", "Request Graph Editor", None))
        self.label.setText(_translate("DemandGraphEditor", "Starting Time:", None))
        self.label_2.setText(_translate("DemandGraphEditor", "End Time:", None))
        self.menuFile.setTitle(_translate("DemandGraphEditor", "File", None))
        self.toolBar.setWindowTitle(_translate("DemandGraphEditor", "toolBar", None))
        self.actionSelect.setText(_translate("DemandGraphEditor", "Select", None))
        self.actionSelect.setShortcut(_translate("DemandGraphEditor", "Alt+1", None))
        self.actionVM.setText(_translate("DemandGraphEditor", "Add VM", None))
        self.actionVM.setToolTip(_translate("DemandGraphEditor", "Add VM", None))
        self.actionVM.setShortcut(_translate("DemandGraphEditor", "Alt+2", None))
        self.actionEdge.setText(_translate("DemandGraphEditor", "Add Virtual Channel", None))
        self.actionEdge.setToolTip(_translate("DemandGraphEditor", "Add Virtual Channel", None))
        self.actionEdge.setShortcut(_translate("DemandGraphEditor", "Alt+3", None))
        self.actionNew_System.setText(_translate("DemandGraphEditor", "New Graph", None))
        self.actionNew_System.setShortcut(_translate("DemandGraphEditor", "Ctrl+N", None))
        self.actionOpen_System.setText(_translate("DemandGraphEditor", "Open Graph", None))
        self.actionOpen_System.setShortcut(_translate("DemandGraphEditor", "Ctrl+O", None))
        self.actionSave_System.setText(_translate("DemandGraphEditor", "Save Graph", None))
        self.actionSave_System.setShortcut(_translate("DemandGraphEditor", "Ctrl+S", None))
        self.actionSave_System_As.setText(_translate("DemandGraphEditor", "Save Graph As...", None))
        self.actionSave_System_As.setShortcut(_translate("DemandGraphEditor", "Ctrl+Shift+S", None))
        self.actionExit.setText(_translate("DemandGraphEditor", "Exit", None))
        self.actionExit.setShortcut(_translate("DemandGraphEditor", "Ctrl+X", None))
        self.actionDemandStorage.setText(_translate("DemandGraphEditor", "Add Storage", None))
        self.actionDemandStorage.setToolTip(_translate("DemandGraphEditor", "Add Storage", None))
        self.actionDemandStorage.setShortcut(_translate("DemandGraphEditor", "Alt+4", None))

from . import resources_rc
