
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(749, 467)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/star.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("QWidget, QMenuBar::item, QHeaderView::section {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #a0a0a0, stop: 1 #f0f0f0);\n"
"}\n"
"\n"
"QLabel, QSlider, QCheckBox {\n"
"    background-color: transparent;\n"
"}"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(_fromUtf8(""))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.projectname = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.projectname.setFont(font)
        self.projectname.setObjectName(_fromUtf8("projectname"))
        self.horizontalLayout_3.addWidget(self.projectname)
        self.editname = QtGui.QPushButton(self.centralwidget)
        self.editname.setMaximumSize(QtCore.QSize(32, 16777215))
        self.editname.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/page_edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editname.setIcon(icon1)
        self.editname.setAutoRepeatInterval(100)
        self.editname.setFlat(True)
        self.editname.setObjectName(_fromUtf8("editname"))
        self.horizontalLayout_3.addWidget(self.editname)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.algorithm = QtGui.QComboBox(self.centralwidget)
        self.algorithm.setMinimumSize(QtCore.QSize(100, 0))
        self.algorithm.setObjectName(_fromUtf8("algorithm"))
        self.algorithm.addItem(_fromUtf8(""))
        self.algorithm.addItem(_fromUtf8(""))
        self.algorithm.addItem(_fromUtf8(""))
        self.algorithm.addItem(_fromUtf8(""))
        self.algorithm.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.algorithm)
        self.runall = QtGui.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runall.setIcon(icon2)
        self.runall.setFlat(True)
        self.runall.setObjectName(_fromUtf8("runall"))
        self.horizontalLayout_4.addWidget(self.runall)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tenants = QtGui.QTreeWidget(self.centralwidget)
        self.tenants.setObjectName(_fromUtf8("tenants"))
        self.tenants.header().setDefaultSectionSize(150)
        self.horizontalLayout_2.addWidget(self.tenants)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_3.addWidget(self.label_13)
        self.tenantcount = QtGui.QLabel(self.groupBox)
        self.tenantcount.setObjectName(_fromUtf8("tenantcount"))
        self.verticalLayout_3.addWidget(self.tenantcount)
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_3.addWidget(self.label_12)
        self.ratio = QtGui.QLabel(self.groupBox)
        self.ratio.setObjectName(_fromUtf8("ratio"))
        self.verticalLayout_3.addWidget(self.ratio)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.netavg = QtGui.QLabel(self.groupBox)
        self.netavg.setObjectName(_fromUtf8("netavg"))
        self.verticalLayout_3.addWidget(self.netavg)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.leafavg = QtGui.QLabel(self.groupBox)
        self.leafavg.setObjectName(_fromUtf8("leafavg"))
        self.verticalLayout_3.addWidget(self.leafavg)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 749, 21))
        self.menubar.setStyleSheet(_fromUtf8(""))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuProject = QtGui.QMenu(self.menubar)
        self.menuProject.setObjectName(_fromUtf8("menuProject"))
        self.menuGenerators = QtGui.QMenu(self.menuProject)
        self.menuGenerators.setObjectName(_fromUtf8("menuGenerators"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionNew_Project = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/page.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionNew_Project.setIcon(icon3)
        self.actionNew_Project.setObjectName(_fromUtf8("actionNew_Project"))
        self.actionOpen_Project = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpen_Project.setIcon(icon4)
        self.actionOpen_Project.setObjectName(_fromUtf8("actionOpen_Project"))
        self.actionSave_Project = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/cd.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSave_Project.setIcon(icon5)
        self.actionSave_Project.setObjectName(_fromUtf8("actionSave_Project"))
        self.actionSave_Project_As = QtGui.QAction(MainWindow)
        self.actionSave_Project_As.setObjectName(_fromUtf8("actionSave_Project_As"))
        self.actionStart = QtGui.QAction(MainWindow)
        self.actionStart.setEnabled(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStart.setIcon(icon6)
        self.actionStart.setObjectName(_fromUtf8("actionStart"))
        self.actionSettings = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon7)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionEdit_Resources = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/graph.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_Resources.setIcon(icon8)
        self.actionEdit_Resources.setObjectName(_fromUtf8("actionEdit_Resources"))
        self.actionAdd_Demand = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Demand.setIcon(icon9)
        self.actionAdd_Demand.setObjectName(_fromUtf8("actionAdd_Demand"))
        self.actionDelete_Demand = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete_Demand.setIcon(icon10)
        self.actionDelete_Demand.setObjectName(_fromUtf8("actionDelete_Demand"))
        self.actionCreate_Random_Demands = QtGui.QAction(MainWindow)
        self.actionCreate_Random_Demands.setEnabled(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/dice.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_Random_Demands.setIcon(icon11)
        self.actionCreate_Random_Demands.setObjectName(_fromUtf8("actionCreate_Random_Demands"))
        self.actionEdit_Demand = QtGui.QAction(MainWindow)
        self.actionEdit_Demand.setIcon(icon1)
        self.actionEdit_Demand.setObjectName(_fromUtf8("actionEdit_Demand"))
        self.actionShow_Results = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/line_chart.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_Results.setIcon(icon12)
        self.actionShow_Results.setObjectName(_fromUtf8("actionShow_Results"))
        self.actionShow_Statistics = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/chart.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_Statistics.setIcon(icon13)
        self.actionShow_Statistics.setObjectName(_fromUtf8("actionShow_Statistics"))
        self.actionReset = QtGui.QAction(MainWindow)
        self.actionReset.setObjectName(_fromUtf8("actionReset"))
        self.actionSchedule_selected = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/fast_forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSchedule_selected.setIcon(icon14)
        self.actionSchedule_selected.setObjectName(_fromUtf8("actionSchedule_selected"))
        self.actionRunMultiple = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/multtests.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRunMultiple.setIcon(icon15)
        self.actionRunMultiple.setObjectName(_fromUtf8("actionRunMultiple"))
        self.actionFds = QtGui.QAction(MainWindow)
        self.actionFds.setObjectName(_fromUtf8("actionFds"))
        self.menuFile.addAction(self.actionNew_Project)
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionSave_Project)
        self.menuFile.addAction(self.actionSave_Project_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuProject.addAction(self.actionEdit_Resources)
        self.menuProject.addAction(self.actionAdd_Demand)
        self.menuProject.addAction(self.actionDelete_Demand)
        self.menuProject.addAction(self.actionEdit_Demand)
        self.menuProject.addAction(self.actionCreate_Random_Demands)
        self.menuProject.addAction(self.menuGenerators.menuAction())
        self.menuProject.addAction(self.actionStart)
        self.menuProject.addAction(self.actionSchedule_selected)
        self.menuProject.addAction(self.actionShow_Statistics)
        self.menuProject.addAction(self.actionShow_Results)
        self.menuProject.addAction(self.actionReset)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.toolBar.addAction(self.actionNew_Project)
        self.toolBar.addAction(self.actionOpen_Project)
        self.toolBar.addAction(self.actionSave_Project)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionEdit_Resources)
        self.toolBar.addAction(self.actionAdd_Demand)
        self.toolBar.addAction(self.actionDelete_Demand)
        self.toolBar.addAction(self.actionEdit_Demand)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addAction(self.actionSchedule_selected)
        self.toolBar.addAction(self.actionShow_Results)
        self.toolBar.addAction(self.actionSettings)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.Exit)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.About)
        QtCore.QObject.connect(self.actionNew_Project, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.NewProject)
        QtCore.QObject.connect(self.actionOpen_Project, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.OpenProject)
        QtCore.QObject.connect(self.actionSave_Project, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.SaveProject)
        QtCore.QObject.connect(self.actionSave_Project_As, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.SaveProjectAs)
        QtCore.QObject.connect(self.actionStart, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.Run)
        QtCore.QObject.connect(self.actionSettings, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.Settings)
        QtCore.QObject.connect(self.actionEdit_Resources, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.EditProgram)
        QtCore.QObject.connect(self.actionAdd_Demand, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.AddTenant)
        QtCore.QObject.connect(self.actionDelete_Demand, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.DeleteTenant)
        QtCore.QObject.connect(self.actionEdit_Demand, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.EditTenant)
        QtCore.QObject.connect(self.actionCreate_Random_Demands, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.RandomTenant)
        QtCore.QObject.connect(self.actionShow_Results, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.ShowResults)
        QtCore.QObject.connect(self.actionReset, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.Reset)
        QtCore.QObject.connect(self.editname, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.EditName)
        QtCore.QObject.connect(self.runall, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.Run)
        QtCore.QObject.connect(self.actionSchedule_selected, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.RunSelected)
        QtCore.QObject.connect(self.actionShow_Statistics, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.ShowGraphVis)
        QtCore.QObject.connect(self.tenants, QtCore.SIGNAL(_fromUtf8("itemChanged(QTreeWidgetItem*,int)")), MainWindow.UpdateTenant)
        QtCore.QObject.connect(self.actionRunMultiple, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.RunMultipleTests)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Data Centers GUI", None))
        self.projectname.setText(_translate("MainWindow", "Project name", None))
        self.label_2.setText(_translate("MainWindow", "Algorithm:", None))
        self.algorithm.setItemText(0, _translate("MainWindow", "Ant Colony", None))
        self.algorithm.setItemText(1, _translate("MainWindow", "Centralized", None))
        self.algorithm.setItemText(2, _translate("MainWindow", "Decentralized", None))
        self.algorithm.setItemText(3, _translate("MainWindow", "FirstFit", None))
        self.algorithm.setItemText(4, _translate("MainWindow", "RandomFit", None))
        self.runall.setText(_translate("MainWindow", "Schedule", None))
        self.tenants.headerItem().setText(0, _translate("MainWindow", "Name", None))
        self.tenants.headerItem().setText(1, _translate("MainWindow", "Allow rescheduling", None))
        self.tenants.headerItem().setText(2, _translate("MainWindow", "Scheduled", None))
        self.groupBox.setTitle(_translate("MainWindow", "Statistics", None))
        self.label_13.setText(_translate("MainWindow", "Total requests scheduled", None))
        self.tenantcount.setText(_translate("MainWindow", "0", None))
        self.label_12.setText(_translate("MainWindow", "Assignment ratio", None))
        self.ratio.setText(_translate("MainWindow", "0", None))
        self.label_9.setText(_translate("MainWindow", "Network load", None))
        self.netavg.setText(_translate("MainWindow", "0", None))
        self.label_4.setText(_translate("MainWindow", "Leaf channels load", None))
        self.leafavg.setText(_translate("MainWindow", "0", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuProject.setTitle(_translate("MainWindow", "Project", None))
        self.menuGenerators.setTitle(_translate("MainWindow", "Generate Requests", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+X", None))
        self.actionAbout.setText(_translate("MainWindow", "About DC GUI", None))
        self.actionAbout.setToolTip(_translate("MainWindow", "About DC GUI", None))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project", None))
        self.actionNew_Project.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project", None))
        self.actionOpen_Project.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSave_Project.setText(_translate("MainWindow", "Save Project", None))
        self.actionSave_Project.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionSave_Project_As.setText(_translate("MainWindow", "Save Project As...", None))
        self.actionSave_Project_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.actionStart.setText(_translate("MainWindow", "Schedule All", None))
        self.actionStart.setToolTip(_translate("MainWindow", "Schedule All", None))
        self.actionStart.setShortcut(_translate("MainWindow", "F5", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings...", None))
        self.actionSettings.setShortcut(_translate("MainWindow", "F12", None))
        self.actionEdit_Resources.setText(_translate("MainWindow", "Edit Resources", None))
        self.actionEdit_Resources.setToolTip(_translate("MainWindow", "Edit Resources", None))
        self.actionEdit_Resources.setShortcut(_translate("MainWindow", "F3", None))
        self.actionAdd_Demand.setText(_translate("MainWindow", "Add Tenant", None))
        self.actionAdd_Demand.setToolTip(_translate("MainWindow", "Add Request", None))
        self.actionAdd_Demand.setShortcut(_translate("MainWindow", "Alt+N", None))
        self.actionDelete_Demand.setText(_translate("MainWindow", "Delete Tenant", None))
        self.actionDelete_Demand.setToolTip(_translate("MainWindow", "Delete Tenant", None))
        self.actionDelete_Demand.setShortcut(_translate("MainWindow", "Alt+X", None))
        self.actionCreate_Random_Demands.setText(_translate("MainWindow", "Create Random Requests", None))
        self.actionCreate_Random_Demands.setToolTip(_translate("MainWindow", "Create Random Requests", None))
        self.actionCreate_Random_Demands.setShortcut(_translate("MainWindow", "F9", None))
        self.actionEdit_Demand.setText(_translate("MainWindow", "Edit Tenant", None))
        self.actionEdit_Demand.setToolTip(_translate("MainWindow", "Edit Tenant", None))
        self.actionEdit_Demand.setShortcut(_translate("MainWindow", "F4", None))
        self.actionShow_Results.setText(_translate("MainWindow", "Show Results", None))
        self.actionShow_Results.setToolTip(_translate("MainWindow", "Show Results", None))
        self.actionShow_Results.setShortcut(_translate("MainWindow", "F7", None))
        self.actionShow_Statistics.setText(_translate("MainWindow", "Show Statistics", None))
        self.actionShow_Statistics.setToolTip(_translate("MainWindow", "Show Statistics", None))
        self.actionShow_Statistics.setShortcut(_translate("MainWindow", "F8", None))
        self.actionReset.setText(_translate("MainWindow", "Reset", None))
        self.actionReset.setShortcut(_translate("MainWindow", "F10", None))
        self.actionSchedule_selected.setText(_translate("MainWindow", "Run All Algorithms", None))
        self.actionSchedule_selected.setShortcut(_translate("MainWindow", "F6, Ctrl+S", None))
        self.actionRunMultiple.setText(_translate("MainWindow", "runMultiple", None))
        self.actionRunMultiple.setToolTip(_translate("MainWindow", "Run Multiple Tests", None))
        self.actionFds.setText(_translate("MainWindow", "fds", None))

from . import resources_rc
