
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName(_fromUtf8("SettingsDialog"))
        SettingsDialog.resize(293, 350)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsDialog.sizePolicy().hasHeightForWidth())
        SettingsDialog.setSizePolicy(sizePolicy)
        SettingsDialog.setMinimumSize(QtCore.QSize(270, 350))
        SettingsDialog.setMaximumSize(QtCore.QSize(293, 350))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SettingsDialog.setWindowIcon(icon)
        SettingsDialog.setStyleSheet(_fromUtf8("QWidget, QMenuBar::item, QHeaderView::section {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #a0a0a0, stop: 1 #f0f0f0);\n"
"}\n"
"\n"
"QLabel, QSlider, QCheckBox {\n"
"    background-color: transparent;\n"
"}"))
        SettingsDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(SettingsDialog)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(SettingsDialog)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.languages = QtGui.QComboBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.languages.setFont(font)
        self.languages.setObjectName(_fromUtf8("languages"))
        self.verticalLayout_2.addWidget(self.languages)
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.params = QtGui.QLineEdit(self.tab_3)
        self.params.setObjectName(_fromUtf8("params"))
        self.horizontalLayout_4.addWidget(self.params)
        self.open = QtGui.QPushButton(self.tab_3)
        self.open.setObjectName(_fromUtf8("open"))
        self.horizontalLayout_4.addWidget(self.open)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.backup = QtGui.QCheckBox(self.tab_3)
        self.backup.setChecked(True)
        self.backup.setObjectName(_fromUtf8("backup"))
        self.verticalLayout_2.addWidget(self.backup)
        self.autosave = QtGui.QCheckBox(self.tab_3)
        self.autosave.setObjectName(_fromUtf8("autosave"))
        self.verticalLayout_2.addWidget(self.autosave)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.interval = QtGui.QSpinBox(self.tab_3)
        self.interval.setProperty("value", 60)
        self.interval.setObjectName(_fromUtf8("interval"))
        self.horizontalLayout_3.addWidget(self.interval)
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_6.addWidget(self.label_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.selection = QtGui.QPushButton(self.groupBox)
        self.selection.setText(_fromUtf8(""))
        self.selection.setObjectName(_fromUtf8("selection"))
        self.verticalLayout_4.addWidget(self.selection)
        self.highlight = QtGui.QPushButton(self.groupBox)
        self.highlight.setText(_fromUtf8(""))
        self.highlight.setObjectName(_fromUtf8("highlight"))
        self.verticalLayout_4.addWidget(self.highlight)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.names = QtGui.QCheckBox(self.groupBox)
        self.names.setChecked(True)
        self.names.setObjectName(_fromUtf8("names"))
        self.verticalLayout_10.addWidget(self.names)
        self.computer = QtGui.QCheckBox(self.groupBox)
        self.computer.setChecked(True)
        self.computer.setObjectName(_fromUtf8("computer"))
        self.verticalLayout_10.addWidget(self.computer)
        self.storage = QtGui.QCheckBox(self.groupBox)
        self.storage.setChecked(True)
        self.storage.setObjectName(_fromUtf8("storage"))
        self.verticalLayout_10.addWidget(self.storage)
        self.router = QtGui.QCheckBox(self.groupBox)
        self.router.setChecked(True)
        self.router.setObjectName(_fromUtf8("router"))
        self.verticalLayout_10.addWidget(self.router)
        self.channel = QtGui.QCheckBox(self.groupBox)
        self.channel.setChecked(True)
        self.channel.setObjectName(_fromUtf8("channel"))
        self.verticalLayout_10.addWidget(self.channel)
        self.verticalLayout_8.addWidget(self.groupBox)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/line_chart.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon1, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton = QtGui.QPushButton(SettingsDialog)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(SettingsDialog)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(SettingsDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsDialog.OK)
        QtCore.QObject.connect(self.selection, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsDialog.SelectionColor)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsDialog.Cancel)
        QtCore.QObject.connect(self.highlight, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsDialog.HighlightColor)
        QtCore.QObject.connect(self.open, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsDialog.OpenParams)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings", None))
        self.label_3.setText(_translate("SettingsDialog", "Language", None))
        self.label_5.setText(_translate("SettingsDialog", "Parameters info", None))
        self.open.setText(_translate("SettingsDialog", "Open", None))
        self.label_4.setText(_translate("SettingsDialog", "Saving Settings", None))
        self.backup.setText(_translate("SettingsDialog", "Backup", None))
        self.autosave.setText(_translate("SettingsDialog", "Auto Save", None))
        self.label_7.setText(_translate("SettingsDialog", "Auto Save Interval:", None))
        self.label_8.setText(_translate("SettingsDialog", "seconds", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SettingsDialog", "General", None))
        self.groupBox.setTitle(_translate("SettingsDialog", "Settings", None))
        self.label.setText(_translate("SettingsDialog", "Selection Color", None))
        self.label_2.setText(_translate("SettingsDialog", "Highlight Color", None))
        self.names.setText(_translate("SettingsDialog", "Show Node Names", None))
        self.computer.setText(_translate("SettingsDialog", "Show Computer Load", None))
        self.storage.setText(_translate("SettingsDialog", "Show Data Store Load", None))
        self.router.setText(_translate("SettingsDialog", "Show Switch Load", None))
        self.channel.setText(_translate("SettingsDialog", "Show Channel Load", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SettingsDialog", "Visualizer", None))
        self.pushButton.setText(_translate("SettingsDialog", "OK", None))
        self.pushButton_2.setText(_translate("SettingsDialog", "Cancel", None))

from . import resources_rc
