
from PyQt4 import QtCore, QtGui

class Ui_TestsWindow(object):
    def setupUi(self, TestsWindow):
        TestsWindow.setObjectName("TestsWindow")
        TestsWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        TestsWindow.resize(521, 359)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pics/pics/multtests.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TestsWindow.setWindowIcon(icon)
        TestsWindow.setStyleSheet("QWidget, QMenuBar::item {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #c5d8ef, stop: 1 #89a5c3);\n"
"}\n"
"\n"
"QLabel, QSlider {\n"
"    background-color: transparent;\n"
"}")
        self.centralwidget = QtGui.QWidget(TestsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tests_tabs = QtGui.QTabWidget(self.centralwidget)
        self.tests_tabs.setEnabled(True)
        self.tests_tabs.setObjectName("tests_tabs")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.algorithm = QtGui.QComboBox(self.tab)
        self.algorithm.setMinimumSize(QtCore.QSize(100, 0))
        self.algorithm.setObjectName("algorithm")
        self.algorithm.addItem("")
        self.algorithm.addItem("")
        self.algorithm.addItem("")
        self.horizontalLayout.addWidget(self.algorithm)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.projects = QtGui.QTreeWidget(self.tab)
        self.projects.setObjectName("projects")
        self.verticalLayout_2.addWidget(self.projects)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.add = QtGui.QPushButton(self.tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pics/pics/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add.setIcon(icon1)
        self.add.setObjectName("add")
        self.verticalLayout.addWidget(self.add)
        self.remove = QtGui.QPushButton(self.tab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pics/pics/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove.setIcon(icon2)
        self.remove.setObjectName("remove")
        self.verticalLayout.addWidget(self.remove)
        self.pushButton = QtGui.QPushButton(self.tab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pics/pics/dice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.run = QtGui.QPushButton(self.tab)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pics/pics/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run.setIcon(icon4)
        self.run.setObjectName("run")
        self.verticalLayout.addWidget(self.run)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.tests_tabs.addTab(self.tab, "")
        self.Graphs = QtGui.QWidget()
        self.Graphs.setObjectName("Graphs")
        self.gridLayout_3 = QtGui.QGridLayout(self.Graphs)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtGui.QLabel(self.Graphs)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.label_3 = QtGui.QLabel(self.Graphs)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.vertical = QtGui.QComboBox(self.Graphs)
        self.vertical.setObjectName("vertical")
        self.vertical.addItem("")
        self.vertical.addItem("")
        self.verticalLayout_3.addWidget(self.vertical)
        self.horizontal = QtGui.QComboBox(self.Graphs)
        self.horizontal.setObjectName("horizontal")
        self.horizontal.addItem("")
        self.horizontal.addItem("")
        self.horizontal.addItem("")
        self.horizontal.addItem("")
        self.horizontal.addItem("")
        self.verticalLayout_3.addWidget(self.horizontal)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.save = QtGui.QPushButton(self.Graphs)
        self.save.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/pics/pics/cd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon5)
        self.save.setObjectName("save")
        self.horizontalLayout_3.addWidget(self.save)
        self.scaledown = QtGui.QPushButton(self.Graphs)
        self.scaledown.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/pics/pics/scaledown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scaledown.setIcon(icon6)
        self.scaledown.setObjectName("scaledown")
        self.horizontalLayout_3.addWidget(self.scaledown)
        self.scaleup = QtGui.QPushButton(self.Graphs)
        self.scaleup.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/pics/pics/scaleup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scaleup.setIcon(icon7)
        self.scaleup.setObjectName("scaleup")
        self.horizontalLayout_3.addWidget(self.scaleup)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.graph = QtGui.QGraphicsView(self.Graphs)
        self.graph.setObjectName("graph")
        self.verticalLayout_5.addWidget(self.graph)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tests_tabs.addTab(self.Graphs, "")
        self.gridLayout.addWidget(self.tests_tabs, 0, 0, 1, 1)
        TestsWindow.setCentralWidget(self.centralwidget)
        self.actionSelect = QtGui.QAction(TestsWindow)
        self.actionSelect.setCheckable(True)
        self.actionSelect.setChecked(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/pics/pics/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelect.setIcon(icon8)
        self.actionSelect.setObjectName("actionSelect")
        self.actionVM = QtGui.QAction(TestsWindow)
        self.actionVM.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/pics/pics/computer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVM.setIcon(icon9)
        self.actionVM.setObjectName("actionVM")
        self.actionEdge = QtGui.QAction(TestsWindow)
        self.actionEdge.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/pics/pics/edge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdge.setIcon(icon10)
        self.actionEdge.setObjectName("actionEdge")
        self.actionNew_System = QtGui.QAction(TestsWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/pics/pics/page.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_System.setIcon(icon11)
        self.actionNew_System.setObjectName("actionNew_System")
        self.actionOpen_System = QtGui.QAction(TestsWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/pics/pics/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_System.setIcon(icon12)
        self.actionOpen_System.setObjectName("actionOpen_System")
        self.actionSave_System = QtGui.QAction(TestsWindow)
        self.actionSave_System.setIcon(icon5)
        self.actionSave_System.setObjectName("actionSave_System")
        self.actionSave_System_As = QtGui.QAction(TestsWindow)
        self.actionSave_System_As.setObjectName("actionSave_System_As")
        self.actionExit = QtGui.QAction(TestsWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionDemandStorage = QtGui.QAction(TestsWindow)
        self.actionDemandStorage.setCheckable(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/pics/pics/storage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDemandStorage.setIcon(icon13)
        self.actionDemandStorage.setObjectName("actionDemandStorage")

        self.retranslateUi(TestsWindow)
        self.tests_tabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.add, QtCore.SIGNAL("clicked()"), TestsWindow.Add)
        QtCore.QObject.connect(self.remove, QtCore.SIGNAL("clicked()"), TestsWindow.Remove)
        QtCore.QObject.connect(self.run, QtCore.SIGNAL("clicked()"), TestsWindow.Run)
        QtCore.QObject.connect(self.vertical, QtCore.SIGNAL("currentIndexChanged(int)"), TestsWindow.Replot)
        QtCore.QObject.connect(self.horizontal, QtCore.SIGNAL("currentIndexChanged(int)"), TestsWindow.Replot)
        QtCore.QObject.connect(self.save, QtCore.SIGNAL("clicked()"), TestsWindow.Save)
        QtCore.QObject.connect(self.scaledown, QtCore.SIGNAL("clicked()"), TestsWindow.ScaleDown)
        QtCore.QObject.connect(self.scaleup, QtCore.SIGNAL("clicked()"), TestsWindow.ScaleUp)
        QtCore.QObject.connect(self.tests_tabs, QtCore.SIGNAL("currentChanged(int)"), TestsWindow.ChangeTab)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), TestsWindow.Generate)
        QtCore.QMetaObject.connectSlotsByName(TestsWindow)

    def retranslateUi(self, TestsWindow):
        TestsWindow.setWindowTitle(QtGui.QApplication.translate("TestsWindow", "Run Multiple Tests", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TestsWindow", "Algorithm:", None, QtGui.QApplication.UnicodeUTF8))
        self.algorithm.setItemText(0, QtGui.QApplication.translate("TestsWindow", "Ant Colony", None, QtGui.QApplication.UnicodeUTF8))
        self.algorithm.setItemText(1, QtGui.QApplication.translate("TestsWindow", "Centralized", None, QtGui.QApplication.UnicodeUTF8))
        self.algorithm.setItemText(2, QtGui.QApplication.translate("TestsWindow", "Decentralized", None, QtGui.QApplication.UnicodeUTF8))
        self.projects.headerItem().setText(0, QtGui.QApplication.translate("TestsWindow", "Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.add.setText(QtGui.QApplication.translate("TestsWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.remove.setText(QtGui.QApplication.translate("TestsWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("TestsWindow", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.run.setText(QtGui.QApplication.translate("TestsWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.tests_tabs.setTabText(self.tests_tabs.indexOf(self.tab), QtGui.QApplication.translate("TestsWindow", "Tests", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TestsWindow", "Vertical axis:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("TestsWindow", "Horizontal axis:", None, QtGui.QApplication.UnicodeUTF8))
        self.vertical.setItemText(0, QtGui.QApplication.translate("TestsWindow", "Number of assigned requests", None, QtGui.QApplication.UnicodeUTF8))
        self.vertical.setItemText(1, QtGui.QApplication.translate("TestsWindow", "Number of replications", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontal.setItemText(0, QtGui.QApplication.translate("TestsWindow", "Computational nodes and data stores load", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontal.setItemText(1, QtGui.QApplication.translate("TestsWindow", "Computational nodes load (CPU and RAM)", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontal.setItemText(2, QtGui.QApplication.translate("TestsWindow", "CPU load", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontal.setItemText(3, QtGui.QApplication.translate("TestsWindow", "RAM load", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontal.setItemText(4, QtGui.QApplication.translate("TestsWindow", "Data stores load", None, QtGui.QApplication.UnicodeUTF8))
        self.tests_tabs.setTabText(self.tests_tabs.indexOf(self.Graphs), QtGui.QApplication.translate("TestsWindow", "Graphs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect.setText(QtGui.QApplication.translate("TestsWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect.setShortcut(QtGui.QApplication.translate("TestsWindow", "Alt+1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVM.setText(QtGui.QApplication.translate("TestsWindow", "Add VM", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVM.setToolTip(QtGui.QApplication.translate("TestsWindow", "Add VM", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVM.setShortcut(QtGui.QApplication.translate("TestsWindow", "Alt+2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdge.setText(QtGui.QApplication.translate("TestsWindow", "Add Virtual Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdge.setToolTip(QtGui.QApplication.translate("TestsWindow", "Add Virtual Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdge.setShortcut(QtGui.QApplication.translate("TestsWindow", "Alt+3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_System.setText(QtGui.QApplication.translate("TestsWindow", "New Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_System.setShortcut(QtGui.QApplication.translate("TestsWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_System.setText(QtGui.QApplication.translate("TestsWindow", "Open Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_System.setShortcut(QtGui.QApplication.translate("TestsWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_System.setText(QtGui.QApplication.translate("TestsWindow", "Save Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_System.setShortcut(QtGui.QApplication.translate("TestsWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_System_As.setText(QtGui.QApplication.translate("TestsWindow", "Save Graph As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_System_As.setShortcut(QtGui.QApplication.translate("TestsWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("TestsWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("TestsWindow", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDemandStorage.setText(QtGui.QApplication.translate("TestsWindow", "Add Storage", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDemandStorage.setToolTip(QtGui.QApplication.translate("TestsWindow", "Add Storage", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDemandStorage.setShortcut(QtGui.QApplication.translate("TestsWindow", "Alt+4", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
