
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TenantVnf(object):
    def setupUi(self, TenantVnf):
        TenantVnf.setObjectName(_fromUtf8("TenantVnf"))
        TenantVnf.resize(324, 825)
        TenantVnf.setStyleSheet(_fromUtf8("QWidget, QMenuBar::item, QHeaderView::section {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #a0a0a0, stop: 1 #f0f0f0);\n"
"}\n"
"\n"
"QLabel, QSlider, QCheckBox, QRadioButton {\n"
"    background-color: transparent;\n"
"}"))
        TenantVnf.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_2 = QtGui.QVBoxLayout(TenantVnf)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.service = QtGui.QCheckBox(TenantVnf)
        self.service.setObjectName(_fromUtf8("service"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.service)
        self.verticalLayout.addLayout(self.formLayout)
        self.normalbutton = QtGui.QRadioButton(TenantVnf)
        self.normalbutton.setChecked(True)
        self.normalbutton.setObjectName(_fromUtf8("normalbutton"))
        self.buttons = QtGui.QButtonGroup(TenantVnf)
        self.buttons.setObjectName(_fromUtf8("buttons"))
        self.buttons.addButton(self.normalbutton)
        self.verticalLayout.addWidget(self.normalbutton)
        self.normal = QtGui.QGroupBox(TenantVnf)
        self.normal.setMinimumSize(QtCore.QSize(0, 0))
        self.normal.setObjectName(_fromUtf8("normal"))
        self.formLayout_3 = QtGui.QFormLayout(self.normal)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_4 = QtGui.QLabel(self.normal)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.name = QtGui.QLineEdit(self.normal)
        self.name.setObjectName(_fromUtf8("name"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.name)
        self.label_5 = QtGui.QLabel(self.normal)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.normal)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.normaltype = QtGui.QLineEdit(self.normal)
        self.normaltype.setObjectName(_fromUtf8("normaltype"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.normaltype)
        self.normalprofile = QtGui.QLineEdit(self.normal)
        self.normalprofile.setObjectName(_fromUtf8("normalprofile"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.normalprofile)
        self.verticalLayout.addWidget(self.normal)
        self.providerbutton = QtGui.QRadioButton(TenantVnf)
        self.providerbutton.setChecked(False)
        self.providerbutton.setObjectName(_fromUtf8("providerbutton"))
        self.buttons.addButton(self.providerbutton)
        self.verticalLayout.addWidget(self.providerbutton)
        self.provider = QtGui.QGroupBox(TenantVnf)
        self.provider.setMinimumSize(QtCore.QSize(0, 0))
        self.provider.setTitle(_fromUtf8(""))
        self.provider.setObjectName(_fromUtf8("provider"))
        self.formLayout_4 = QtGui.QFormLayout(self.provider)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_7 = QtGui.QLabel(self.provider)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.provider)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.provider)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.provider)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(self.provider)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtGui.QLabel(self.provider)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_12)
        self.providervnfname = QtGui.QLineEdit(self.provider)
        self.providervnfname.setObjectName(_fromUtf8("providervnfname"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.providervnfname)
        self.providervnftype = QtGui.QLineEdit(self.provider)
        self.providervnftype.setObjectName(_fromUtf8("providervnftype"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.providervnftype)
        self.providervnfprofile = QtGui.QLineEdit(self.provider)
        self.providervnfprofile.setObjectName(_fromUtf8("providervnfprofile"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.providervnfprofile)
        self.providerusername = QtGui.QLineEdit(self.provider)
        self.providerusername.setObjectName(_fromUtf8("providerusername"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.providerusername)
        self.providerservicename = QtGui.QLineEdit(self.provider)
        self.providerservicename.setObjectName(_fromUtf8("providerservicename"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.providerservicename)
        self.providerset = QtGui.QLineEdit(self.provider)
        self.providerset.setObjectName(_fromUtf8("providerset"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.providerset)
        self.verticalLayout.addWidget(self.provider)
        self.userbutton = QtGui.QRadioButton(TenantVnf)
        self.userbutton.setObjectName(_fromUtf8("userbutton"))
        self.buttons.addButton(self.userbutton)
        self.verticalLayout.addWidget(self.userbutton)
        self.user = QtGui.QGroupBox(TenantVnf)
        self.user.setMinimumSize(QtCore.QSize(0, 0))
        self.user.setTitle(_fromUtf8(""))
        self.user.setObjectName(_fromUtf8("user"))
        self.formLayout_5 = QtGui.QFormLayout(self.user)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_18 = QtGui.QLabel(self.user)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_18)
        self.username = QtGui.QLineEdit(self.user)
        self.username.setObjectName(_fromUtf8("username"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.username)
        self.label_17 = QtGui.QLabel(self.user)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_17)
        self.usertype = QtGui.QLineEdit(self.user)
        self.usertype.setObjectName(_fromUtf8("usertype"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.usertype)
        self.label_16 = QtGui.QLabel(self.user)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_16)
        self.userprovider = QtGui.QLineEdit(self.user)
        self.userprovider.setObjectName(_fromUtf8("userprovider"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.userprovider)
        self.label_14 = QtGui.QLabel(self.user)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_14)
        self.userservice = QtGui.QLineEdit(self.user)
        self.userservice.setObjectName(_fromUtf8("userservice"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.userservice)
        self.label_15 = QtGui.QLabel(self.user)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_15)
        self.userset = QtGui.QLineEdit(self.user)
        self.userset.setObjectName(_fromUtf8("userset"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.userset)
        self.userrouter = QtGui.QCheckBox(self.user)
        self.userrouter.setObjectName(_fromUtf8("userrouter"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.LabelRole, self.userrouter)
        self.userip = QtGui.QLineEdit(self.user)
        self.userip.setObjectName(_fromUtf8("userip"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.FieldRole, self.userip)
        self.verticalLayout.addWidget(self.user)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(TenantVnf)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.add = QtGui.QPushButton(TenantVnf)
        self.add.setMaximumSize(QtCore.QSize(16, 16777215))
        self.add.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add.setIcon(icon)
        self.add.setFlat(True)
        self.add.setObjectName(_fromUtf8("add"))
        self.horizontalLayout_5.addWidget(self.add)
        self.remove = QtGui.QPushButton(TenantVnf)
        self.remove.setMaximumSize(QtCore.QSize(16, 16777215))
        self.remove.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove.setIcon(icon1)
        self.remove.setFlat(True)
        self.remove.setObjectName(_fromUtf8("remove"))
        self.horizontalLayout_5.addWidget(self.remove)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.params = QtGui.QTableWidget(TenantVnf)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.params.sizePolicy().hasHeightForWidth())
        self.params.setSizePolicy(sizePolicy)
        self.params.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.params.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.params.setShowGrid(True)
        self.params.setColumnCount(3)
        self.params.setObjectName(_fromUtf8("params"))
        self.params.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.params.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.params.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.params.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_4.addWidget(self.params)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.OK = QtGui.QPushButton(TenantVnf)
        self.OK.setObjectName(_fromUtf8("OK"))
        self.horizontalLayout.addWidget(self.OK)
        self.Cancel = QtGui.QPushButton(TenantVnf)
        self.Cancel.setObjectName(_fromUtf8("Cancel"))
        self.horizontalLayout.addWidget(self.Cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(TenantVnf)
        QtCore.QObject.connect(self.OK, QtCore.SIGNAL(_fromUtf8("clicked()")), TenantVnf.accept)
        QtCore.QObject.connect(self.Cancel, QtCore.SIGNAL(_fromUtf8("clicked()")), TenantVnf.reject)
        QtCore.QObject.connect(self.add, QtCore.SIGNAL(_fromUtf8("clicked()")), TenantVnf.AddParam)
        QtCore.QObject.connect(self.remove, QtCore.SIGNAL(_fromUtf8("clicked()")), TenantVnf.RemoveParam)
        QtCore.QObject.connect(self.normalbutton, QtCore.SIGNAL(_fromUtf8("clicked()")), TenantVnf.RadioClick)
        QtCore.QObject.connect(self.providerbutton, QtCore.SIGNAL(_fromUtf8("clicked()")), TenantVnf.RadioClick)
        QtCore.QObject.connect(self.userbutton, QtCore.SIGNAL(_fromUtf8("clicked()")), TenantVnf.RadioClick)
        QtCore.QMetaObject.connectSlotsByName(TenantVnf)

    def retranslateUi(self, TenantVnf):
        TenantVnf.setWindowTitle(_translate("TenantVnf", "Edit Vnf", None))
        self.service.setText(_translate("TenantVnf", "Service", None))
        self.normalbutton.setText(_translate("TenantVnf", "Normal", None))
        self.label_4.setText(_translate("TenantVnf", "Name:", None))
        self.label_5.setText(_translate("TenantVnf", "Type:", None))
        self.label_6.setText(_translate("TenantVnf", "Profile type:", None))
        self.providerbutton.setText(_translate("TenantVnf", "Service as provider", None))
        self.label_7.setText(_translate("TenantVnf", "VNF name:", None))
        self.label_8.setText(_translate("TenantVnf", "VNF type:", None))
        self.label_9.setText(_translate("TenantVnf", "VNF profile type:", None))
        self.label_10.setText(_translate("TenantVnf", "User name:", None))
        self.label_11.setText(_translate("TenantVnf", "Exported connection set:", None))
        self.label_12.setText(_translate("TenantVnf", "Service name:", None))
        self.userbutton.setText(_translate("TenantVnf", "Service as user", None))
        self.label_18.setText(_translate("TenantVnf", "Netelement name:", None))
        self.label_17.setText(_translate("TenantVnf", "Netelement type:", None))
        self.label_16.setText(_translate("TenantVnf", "Provider name:", None))
        self.label_14.setText(_translate("TenantVnf", "Service name:", None))
        self.label_15.setText(_translate("TenantVnf", "Imported connection set:", None))
        self.userrouter.setText(_translate("TenantVnf", "Router           IP:", None))
        self.label_3.setText(_translate("TenantVnf", "Parameters:", None))
        item = self.params.horizontalHeaderItem(0)
        item.setText(_translate("TenantVnf", "Name", None))
        item = self.params.horizontalHeaderItem(1)
        item.setText(_translate("TenantVnf", "Type", None))
        item = self.params.horizontalHeaderItem(2)
        item.setText(_translate("TenantVnf", "Value", None))
        self.OK.setText(_translate("TenantVnf", "OK", None))
        self.Cancel.setText(_translate("TenantVnf", "Cancel", None))

from . import resources_rc
